"""Checks on cloudshell/run-all.sh.

The script inlines the project deliverables so it can be pasted into AWS
CloudShell as a single self-contained command. That duplication is the point,
but it can drift: edit `system_prompt.txt` in the repo and the CloudShell run
would silently deploy the old prompt. These tests make that a build failure.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess

import pytest

SCRIPT_REL = "cloudshell/run-all.sh"


@pytest.fixture(scope="module")
def script(request) -> str:
    path = request.config.rootpath / SCRIPT_REL
    assert path.exists(), f"{SCRIPT_REL} is missing"
    return path.read_text(encoding="utf-8")


def _heredoc(script: str, delim: str) -> str | None:
    """Pull the body of a quoted heredoc out of the script."""
    match = re.search(rf"<<'{delim}'\n(.*?)\n{delim}\n", script, re.S)
    return match.group(1) + "\n" if match else None






def _working_bash() -> str | None:
    """A bash that actually runs.

    On Windows ``shutil.which("bash")`` often finds the WSL stub, which fails
    with an exec error if no distro is installed. Probe before trusting it,
    and fall back to Git Bash.
    """
    candidates = [
        shutil.which("bash"),
        r"C:\Program Files\Git\bin\bash.exe",
        r"C:\Program Files\Git\usr\bin\bash.exe",
    ]
    for candidate in candidates:
        if not candidate:
            continue
        try:
            probe = subprocess.run(
                [candidate, "-c", "exit 0"], capture_output=True, timeout=20
            )
        except (OSError, subprocess.SubprocessError):
            continue
        if probe.returncode == 0:
            return candidate
    return None


def test_the_script_is_valid_bash(request):
    bash = _working_bash()
    if bash is None:
        pytest.skip("no working bash on this machine")
    path = request.config.rootpath / SCRIPT_REL

    result = subprocess.run(
        [bash, "-n", str(path)], capture_output=True, text=True
    )

    assert result.returncode == 0, result.stderr


def test_it_pins_the_region_and_model_the_course_requires(script):
    assert 'REGION="${REGION:-us-east-1}"' in script
    assert "us.amazon.nova-pro-v1:0" in script


def test_it_checks_nova_access_before_deploying_anything(script):
    """Model access is the most common blocker. Failing fast on it saves
    several minutes of CloudFormation before the real error appears."""
    nova_check = script.index("bedrock-runtime converse")
    first_deploy = script.index("cloudformation deploy")

    assert nova_check < first_deploy, "the Nova access check must come first"


def test_it_never_destroys_working_resources(script):
    """Teardown is printed for the user to run, not executed - the evidence
    has to survive the run.

    The one exception is a stack stuck in ROLLBACK_COMPLETE or CREATE_FAILED:
    CloudFormation cannot update those, so they have to be deleted before a
    redeploy. That is checked separately below.
    """
    body = script.split("Tear down when you are done")[0]

    for destructive in ("s3 rm", "cleanup_agentcore.py", "delete_harness"):
        assert destructive not in body, (
            f"{destructive!r} runs during the script; it should only appear in "
            "the teardown instructions printed at the end"
        )


def test_stack_deletion_only_happens_to_recover_a_failed_stack(script):
    """Every delete-stack in the body must sit in a branch guarded by a failed
    stack status - never on a healthy stack."""
    body = script.split("Tear down when you are done")[0]

    for match in re.finditer(r"^.*delete-stack.*$", body, re.M):
        preceding = body[: match.start()]
        # The nearest case-branch label above this line.
        guards = re.findall(r"^\s*([A-Z_|]*(?:ROLLBACK_COMPLETE|CREATE_FAILED)[A-Z_|]*)\)",
                            preceding, re.M)
        assert guards, (
            f"unguarded stack deletion: {match.group(0).strip()!r}"
        )


def test_a_recovered_stack_is_waited_on_before_redeploy(script):
    """Deleting a stack is asynchronous - redeploying before it finishes fails
    with AlreadyExistsException."""
    assert script.count("wait stack-delete-complete") >= 2


def test_it_is_resumable(script):
    """CloudShell sessions drop. Re-running must not duplicate resources."""
    assert "cfn_status" in script
    assert 'cfg_get gateway_id' in script
    assert "already deployed" in script


def test_it_writes_both_test_suite_filenames(script):
    """The rubric says flow-tests.json, the instructions say
    harness-tests.json."""
    assert "cp harness-tests.json flow-tests.json" in script


# --- the self-extracting paste ---------------------------------------------
#
# PASTE-THIS.txt is generated by cloudshell/regenerate-paste.sh. It carries the
# gzipped script as base64 inside a quoted heredoc, wrapped at 76 columns, and
# verifies a sha256 after decoding.
#
# An earlier version was a single 20KB `echo <blob> | base64 -d` line. It got
# truncated on paste into CloudShell and surfaced as "gunzip: invalid
# compressed data - format violated", with no clue what had gone wrong. Hence
# both the wrapping and the checksum.


import base64
import gzip
import hashlib

PASTE_REL = "cloudshell/PASTE-THIS.txt"


def _payload(paste: str) -> bytes:
    """The decoded script the paste would write."""
    match = re.search(r"<<'B64_EOF'\n(.*?)\nB64_EOF\n", paste, re.S)
    assert match, "PASTE-THIS.txt has no B64_EOF heredoc"
    return gzip.decompress(base64.b64decode(match.group(1)))


@pytest.fixture(scope="module")
def paste(request) -> str:
    return (request.config.rootpath / PASTE_REL).read_text(encoding="utf-8")


def test_the_paste_decodes_to_the_script(request, paste):
    script = (request.config.rootpath / SCRIPT_REL).read_bytes()

    assert _payload(paste) == script, (
        "PASTE-THIS.txt is stale - run cloudshell/regenerate-paste.sh"
    )


def test_the_embedded_checksum_matches_the_script(request, paste):
    """The paste verifies this hash after decoding; a stale hash would make
    every correct paste report itself as corrupted."""
    script = (request.config.rootpath / SCRIPT_REL).read_bytes()
    expected = hashlib.sha256(script).hexdigest()

    assert expected in paste, (
        "the sha256 baked into PASTE-THIS.txt does not match run-all.sh - "
        "run cloudshell/regenerate-paste.sh"
    )


def test_no_line_is_long_enough_to_be_mangled_on_paste(paste):
    """The bug that broke the first version was a single ~20,000 character
    line, which terminal paste truncated. Ordinary shell-length lines are
    fine; the payload itself must stay wrapped."""
    lines = paste.splitlines()
    longest = max(len(line) for line in lines)

    assert longest <= 200, f"longest line is {longest} chars; wrap the base64"

    # The base64 body specifically - the only part big enough to matter.
    body = re.search(r"<<'B64_EOF'\n(.*?)\nB64_EOF\n", paste, re.S).group(1)
    widest = max(len(line) for line in body.splitlines())

    assert widest <= 80, f"base64 wrapped at {widest} columns; use 76"


def test_a_corrupted_paste_reports_itself_clearly(paste):
    """Rather than leaving the user staring at a gunzip error."""
    assert "PASTE INCOMPLETE OR CORRUPTED" in paste
    assert "Upload file" in paste, "the fallback route must be spelled out"
    assert "sha256sum" in paste


def test_the_base64_survives_word_splitting(paste):
    """It is read from a file by `base64 -d`, never interpolated into an
    unquoted `echo` - that was the other half of the original bug."""
    assert "<<'B64_EOF'" in paste, "the heredoc must be quoted"
    assert "base64 -d /tmp/ra.b64" in paste
    assert not re.search(r"echo \$?[A-Za-z0-9+/=]{100,}", paste), (
        "the payload must not be echoed as a shell word"
    )


def test_the_decoded_paste_has_unix_line_endings(paste):
    decoded = _payload(paste)

    assert b"\r\n" not in decoded, "the paste would write a CRLF script"
    assert decoded.startswith(b"#!/usr/bin/env bash\n")


def test_the_runner_exercises_the_guardrail(script):
    """The guardrail is a stand-out item; building it without running it
    proves nothing."""
    assert "setup_guardrail.py" in script
    assert "guardrail.screen" in script


def test_the_guardrail_step_is_not_fatal(script):
    """It is an extra, so a failure there must not abort a run that is
    otherwise producing submission evidence."""
    assert "python setup_guardrail.py || GUARDRAIL_OK=0" in script


def test_the_runner_bundles_evidence(script):
    """Everything the rubric asks for, in one downloadable file."""
    assert "evidence.tar.gz" in script
    for artefact in ("rendered_system_prompt.txt", "dynamodb_bug_reports.json",
                     "run_summary.txt", "output_eval_dataset.jsonl"):
        assert artefact in script, f"{artefact} is not bundled"


def test_the_rendered_prompt_is_captured(script):
    """The AgentCore stand-in for the rubric's 'FAQ Prompt node template
    showing embedded FAQ content' - the prompt with {{FAQ}} substituted."""
    assert 'replace("{{FAQ}}", faq)' in script


# --- the generated inlined-deliverables block ------------------------------
#
# run-all.sh carries copies of the project's own files so it can be pasted
# into CloudShell. Hand-maintaining them went wrong twice: an edited prompt
# that was never re-inlined, and a call to setup_guardrail.py wired in while
# the file itself was not, which killed step 10 on a live run. The block is
# generated from cloudshell/sync-inline.py's INLINED list now, and these tests
# hold that contract.


def _inlined_names(request) -> list[str]:
    sync = (request.config.rootpath / "cloudshell" / "sync-inline.py").read_text(
        encoding="utf-8"
    )
    block = re.search(r"INLINED = \[(.*?)\n\]", sync, re.S).group(1)
    return re.findall(r'"([^"]+)"', block)


def test_every_inlined_file_is_written_by_the_script(request, script):
    for name in _inlined_names(request):
        assert f"cat > {name} <<" in script, f"{name} is listed but not written"


def test_every_inlined_file_matches_project_starter(request, script, starter_dir):
    """The prompt regression: edit project/starter, forget to re-inline, and
    CloudShell silently deploys the old version."""
    for name in _inlined_names(request):
        delim = "INLINE_" + name.replace(".", "_").replace("-", "_").upper()
        inlined = _heredoc(script, delim)

        assert inlined is not None, f"no {delim} heredoc for {name}"
        wanted = (starter_dir / name).read_text(encoding="utf-8")
        assert inlined == wanted, (
            f"the inlined {name} differs from project/starter/{name} - "
            "run cloudshell/regenerate-paste.sh"
        )


def test_every_python_script_it_runs_actually_exists(request, script):
    """The bug this exists for: `python setup_guardrail.py` was wired into
    step 10 while the file was never inlined, so a live run failed with
    "No such file or directory"."""
    # Files the script clones from the Udacity starter repo.
    from_starter = {
        "chat.py", "cleanup_agentcore.py", "create_bug_report.py",
        "create_harness.py", "generate-eval-dataset.py", "setup_gateway.py",
    }
    available = set(_inlined_names(request)) | from_starter

    invoked = set(re.findall(r"^\s*python3? ([A-Za-z0-9_-]+\.py)", script, re.M))

    missing = invoked - available
    assert not missing, (
        f"run-all.sh runs {sorted(missing)} but neither inlines them nor gets "
        "them from the starter repo"
    )


def test_the_generated_block_has_its_markers(script):
    assert "# >>> BEGIN INLINED DELIVERABLES" in script
    assert "# <<< END INLINED DELIVERABLES" in script
    assert "do not edit by hand" in script


def test_memory_is_scoped_before_any_test_runs(script):
    """Cross-session recall made every test depend on what ran before it, so
    it has to be turned off before the bug report and the eval dataset."""
    # Search only the executable part: the inlined files contain these
    # same strings inside their own docstrings.
    body = script[script.index("# <<< END INLINED DELIVERABLES"):]
    disable = body.index("python disable_memory.py")
    bug_report = body.index("python scripted_bug_report.py")
    dataset = body.index("generate-eval-dataset.py --tests-json")

    assert disable < bug_report, "memory must be scoped before the bug report"
    assert disable < dataset, "memory must be scoped before the eval dataset"


# --- the IAM user bootstrap ------------------------------------------------


PASTES = [
    ("cloudshell/PASTE-THIS.txt", "cloudshell/run-all.sh"),
    ("cloudshell/PASTE-CREATE-USER.txt", "cloudshell/create-evidence-user.sh"),
]


@pytest.mark.parametrize("paste_rel,script_rel", PASTES)
def test_each_paste_decodes_to_its_script(request, paste_rel, script_rel):
    paste = (request.config.rootpath / paste_rel).read_text(encoding="utf-8")
    script = (request.config.rootpath / script_rel).read_bytes()

    decoded = _payload(paste)

    assert decoded == script, (
        f"{paste_rel} is stale - run cloudshell/regenerate-paste.sh"
    )
    assert b"\r\n" not in decoded, f"{paste_rel} would write a CRLF script"


@pytest.mark.parametrize("paste_rel,script_rel", PASTES)
def test_each_paste_verifies_its_own_checksum(request, paste_rel, script_rel):
    import hashlib

    paste = (request.config.rootpath / paste_rel).read_text(encoding="utf-8")
    script = (request.config.rootpath / script_rel).read_bytes()

    assert hashlib.sha256(script).hexdigest() in paste
    assert "PASTE INCOMPLETE OR CORRUPTED" in paste


def test_the_user_script_grants_federation_explicitly(request):
    """ReadOnlyAccess does not cover sts:GetFederationToken - it is not a read
    action - so without an explicit grant the console URL cannot be minted."""
    src = (request.config.rootpath / "cloudshell" / "create-evidence-user.sh").read_text(
        encoding="utf-8"
    )

    assert "sts:GetFederationToken" in src
    assert "arn:aws:iam::aws:policy/ReadOnlyAccess" in src


def test_the_user_script_is_read_only(request):
    """The whole point is a credential that can look at the console and
    nothing else. It must not attach an admin policy."""
    src = (request.config.rootpath / "cloudshell" / "create-evidence-user.sh").read_text(
        encoding="utf-8"
    )

    for dangerous in ("AdministratorAccess", "PowerUserAccess", "IAMFullAccess"):
        assert dangerous not in src, f"{dangerous} must not be attached"


def test_the_user_script_can_clean_up_after_itself(request):
    """Leaving a long-lived access key behind is the failure mode here."""
    src = (request.config.rootpath / "cloudshell" / "create-evidence-user.sh").read_text(
        encoding="utf-8"
    )

    assert "--delete" in src
    assert "delete-access-key" in src
    assert "delete-user" in src
    assert "history -c" in src, "should tell the user to wipe the printed secret"
