#!/usr/bin/env python3
"""Generate run-all.sh's inlined-deliverables block from project/starter.

run-all.sh has to be self-contained so it can be pasted into CloudShell, which
means carrying copies of the project's own files. Hand-maintaining those copies
went wrong twice:

  * the prompt was edited in project/starter and the CloudShell run kept
    deploying the old one;
  * a call to setup_guardrail.py was wired into the script while the file
    itself was never inlined, so step 10 died with "No such file or directory"
    on a live run.

Both are the same mistake, so the block is now generated from ``INLINED``
below. Adding a file to that list is the only step needed — the heredoc, the
progress line and the chmod all follow.

    bash cloudshell/regenerate-paste.sh     # calls this, then re-encodes

The test suite asserts the generated block matches project/starter, so a
forgotten sync fails the build instead of the deploy.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
STARTER = HERE.parent / "project" / "starter"
SCRIPT = HERE / "run-all.sh"

BEGIN = "# >>> BEGIN INLINED DELIVERABLES"
END = "# <<< END INLINED DELIVERABLES"

# Files run-all.sh writes into project/starter before it runs anything.
# Order matters only for the progress output.
INLINED = [
    "system_prompt.txt",       # the deliverable
    "harness-tests.json",      # the evaluation suite
    "scripted_bug_report.py",  # live multi-turn check + DynamoDB verification
    "run_evaluation.py",       # upload + create the evaluation job
    "disable_memory.py",       # turn off cross-session recall
    "guardrail.py",            # the ApplyGuardrail pre-screen
    "setup_guardrail.py",      # creates the guardrail
]

EXECUTABLE = {".py", ".sh"}


def heredoc(filename: str) -> str:
    """One `cat > file <<'DELIM' ... DELIM` stanza."""
    source = STARTER / filename
    if not source.exists():
        raise SystemExit(f"error: {source} does not exist")

    body = source.read_text(encoding="utf-8").replace("\r\n", "\n")
    if body.endswith("\n"):
        body = body[:-1]

    delim = "INLINE_" + filename.replace(".", "_").replace("-", "_").upper()
    if any(line == delim for line in body.split("\n")):
        raise SystemExit(f"error: {filename} contains a line equal to {delim}")

    out = [f'info "writing {filename}"',
           f"cat > {filename} <<'{delim}'",
           body,
           delim]
    if source.suffix in EXECUTABLE:
        out.append(f"chmod +x {filename}")
    return "\n".join(out)


def main() -> int:
    script = SCRIPT.read_text(encoding="utf-8", newline="\n")

    if BEGIN not in script or END not in script:
        raise SystemExit(
            f"error: {SCRIPT.name} has no {BEGIN} / {END} markers"
        )

    start = script.index(BEGIN)
    stop = script.index(END) + len(END)

    generated = "\n".join([
        BEGIN,
        "# Generated by cloudshell/sync-inline.py - do not edit by hand.",
        "",
        *[heredoc(name) for name in INLINED],
        "",
        END,
    ])

    if script[start:stop] == generated:
        print(f"inlined block already up to date ({len(INLINED)} files)")
        return 0

    SCRIPT.write_text(
        script[:start] + generated + script[stop:], encoding="utf-8", newline="\n"
    )
    total = sum((STARTER / n).stat().st_size for n in INLINED)
    print(f"re-inlined {len(INLINED)} files ({total:,} bytes): "
          + ", ".join(INLINED))
    return 0


if __name__ == "__main__":
    sys.exit(main())
